[FIREBASE]
type = "service_account"
project_id = "cse331-77111"
private_key_id = "ef779cd6e3f71e590642e8cfebf7856e04f7817b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDUJdTSKq/je1q1
7ws+ZRyJrnGvcYXWYFJTt+BxQEjqd1wfDH+1kOnCQOPSesJlMu9LJCIl4c7SvqQv
M/KWO/66ruIaB9OrxcsDtk35a1H/oDHrcOUtqNau/W2+QojRZGjKb2H+nAi6A4Rj
Nw45RER7VqQGuy79s9c9CggXi8pdOEBzNPU7qrAjrby09SEKW8FiVYmiV45z6RLH
G4F5IHQhocgSkp+vug2YJ2zpzMbJodLIMDaxreKAa13DCP4uEyUSpTEknvDy7UZ/
w3phHk/NvKFAQDHzF5S5WBi1P1X3M4Y40fR4wSpfuG770sqY1SCkRzgixeJ4Eo7b
Ym5vF8KtAgMBAAECggEADWyTafUfiiJ9G/QTXxBg3Ol38iUZ1fXkX73L6v6pXoTN
BH3y+tc/o3YdtGzmLicp8zRHIOSIBNfhZcdAu3byaHe2gPUr1LvAW+zGRFkhKC7H
2eEb72a2pv4MWrS1GaLj6qNfrQ/MkZC1aN3L/Z2vQ6q42GAx2gXuQcOHvY2v8XQH
R1yJm3F3xEE6i5X360pl3dl+4335zWNReM92mWPnOBbTlr0md09AITlri1lel7mA
WDOfZi/HCDtgWfJVKucaP9CLECpncXC4dF22RsOxdvYoaxYOKyQiPXqzHepROEdM
RF1mTSsrJDnKFC4tLQYziblHj/fCZgHwmhtmYD++oQKBgQDu89WAImmO1jgQ2lpL
RMxqEVsSZgAG3/RaO2pyRdMtKEHc8hl8p+lAzA6A5/+iWd9HqD8a7N1O/cNmu9/P
rmZwCJJNfVPiYrH2CiB7R0zD0dQlK1lakbVsX3BeYXIIDS4qKvCaadVYO5YmFzEQ
oP72ewygIyccZK89KqP/At7AmQKBgQDjSHF8IyB2E63rweFssF3So+xIoRiLoTiC
tT2ofQozCQ034sIHaIEjr4sjpCkAkJhgbMymXhU1Pvkq3MVa3nozmAHMFw9TN+JN
3IhZwTxjwagy6jdSxO/+Jpwxje0WcU3cOrfD9Ekzh2b5E4glzOj1Qws6ZgM/8qZC
kDYaQU/bNQKBgQCsR8sv5h+7J0InDHc7e2/yLW8/FaGBU2jmwZ3eo+88yKCr/zVX
Be0LldQDJsHNuQRdsrVE4XAyao2+fUhBgVlD/zoUen7HYycx4F1I5MA5Ewjkf5ud
zB5E846dzZ4cpfwZ1PnCKvnx8owwDFqIxbrt1QvmTVH+i6046Yxx6QzXSQKBgQCx
5uh9hHlKM0k1eoLasood8JVonEA8Oyuik/75PTaYkAM6tVGuvswmhKdidIJroMLE
5yShLI9pKCucs0X/RJlefSMa/wnN17ZZv78ykiCU7OadQ9ud++zmgI5N84uav4F0
Wrmwtiv+G4Qsfm9ZNzU5lQra4TK2AVbGT18p2emJ6QKBgQDmeAIq/jSUZCB6IFBt
GenmzvugAoyD46HOOCTgaMvJyWyyPYXbperdrlCh6a90ZLLM31p7hcANPRT60YEB
ZvvhH3r6RuWqWx2JYs+bOLJXlgTmSIs5RNERW1PSpfasTqzsYHo2aJ2cDkRShbFb
mJdwfztZShyAgkibop4TV5FZnQ==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@cse331-77111.iam.gserviceaccount.com"
client_id = "114000379991722929475"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40cse331-77111.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
